### ISSUE TITLE
배포 Profile 기능 구현

### ISSUE THREAD

**Issue by chj777** [LEEHWIJIN/internsheep-front#139]
PROFILE 기능으로 서버설정과 로컬 설정을 구분하여 사용할 수 있어야 한다.

**Comment by headcha** [comment]
배포 프로파일은 적용했다가 설명해줘야 하는게 더 길어서 상수를 사용하는 방법으로 예제를 만들어둠

@chj777 @hol819 @LEEHWIJIN @SUYEON97
