### ISSUE TITLE
학생_이력서 기능 구현

### ISSUE THREAD

**Issue by chj777** [LEEHWIJIN/internsheep-front#19]
[요구사항]
 1. 이름, 학번을 input 값에 입력받는다.
 2. data형식을 정의하고 axios로 보낸다.

[완료조건]
 1. console에 찍어서 [이름, 학번]이 저장버튼을 눌렀을 때 제대로 넘어가는지 확인하기.

**Comment by LEEHWIJIN** [comment]
구현 완료.
