### ISSUE TITLE
학생_보고서 및 후기 관리 기능 구현

### ISSUE THREAD

**Issue by chj777** [LEEHWIJIN/internsheep-front#25]

**Comment by LEEHWIJIN** [comment]
formData 라는 것을 알게 됨.
formData를 사용하여 첨부된 파일과 내가 작성한 후기를 formdata.append()를 사용하여 axios를 통해 http://localhost:8888/std/mypage/postReportAndReview 이곳으로 넘김.

formdata를 써서 파일을 넘길땐 꼭 header에 'Content-Type' : 'multipart/form-data' 라는 것을 써서 넘겨야 됨.
그리고 formdata는 console.log로 확인할 수 없음
key value 형태라서 key와 value를 출력해봐야함!

**Comment by SUYEON97** [comment]
created()에 downloadButton(학생이 저장한 보고서를 계속 받아옴) 과 loadFileName(학생이 저장한 파일 이름을 가져옴)를 넣어 처음에 불러오도록함

파일을 저장하는 방식은 a태그 download방식으로 저장함
a 태그 download 방식을 사용함 
이 방식은 형식이 <a href ='파일이 저장되어 있는 url' download></a>임
이 때 이 url은 http:// 형식이여 야함 c:// 형식이면 다운로드가 안됨 a태그는 단순히 url로 넘겨 다운로드 받는 것이라 검색창에 그냥 넣었을 때도 다운로드 받을 수 있는 경로를 넘겨야함 그래서 백에서 res.download()로 넘겨주는 url을 넣어줌

학생은 자신이 저장한 파일 이름을 누르면 바로 다운로드를 할 수 있음

보완 할점 : 다운로드 받을 때는 서버에서 저장한 이름으로 받아와 진다. 이것을 학생이 저장한 이름으로 바꾸기 
학생이 자신이 저장한 보고서를 업데이트 하고 나면 페이지가 다시 재 로딩 되어야한다. (새로고침)
