### ISSUE TITLE
학생_보고서 및 후기 관리 API 구현

### ISSUE THREAD

**Issue by chj777** [LEEHWIJIN/internsheep-front#26]

**Comment by LEEHWIJIN** [comment]
보고서 및 후기 post api 구현
express 에서 multer 라는 api 를 사용하여 file 주고 받는 것을 구현
file은 multer라는 것의 도움을 받아야 첨부 할 수 있다는 것을 배움.
출처 : https://wayhome25.github.io/nodejs/2017/02/21/nodejs-15-file-upload/

**Comment by SUYEON97** [comment]
1. 보고서 및 후기 등록(post)
라우터 : /std/mypage/postReportAndReview
companyReview 테이블과 report 테이블에 insert함 
multer를 사용해 파일 destination 은 './upload/'에 저장하고 이름은 학생 '학번 + 학생이 저장한 이름'으로 함
companyReview 테이블에는 회사이름(cName), 별점(starScore), 학생이름(sName)을 저장함
report테이블에는 학생이름(sName) , 학생학번(sNum) , 저장한 이름(reportURL) , 학생이 저장한 이름(reportRealName)을 저장함
이때 저장된 이름은 req.file.path 로 가져올 수 있음. 나머지는 body로 가져옴

2. 자신이 작성한 보고서 이름 가져오기(get)
라우터 : /std/mypage/loadFileName
프론트에서 학생이 저장한 이름을 보여주기 위해 sName을 받아와 학생을 찾고 만약 학생이 보고서를 저장한 적이 없으면 ''을 보내주고 있다면 학생이 저장한 이름(reportRealName)을 보내준다.

3. 자신이 저장한 보고서 다운로드 받기(get) 
라우터 : /std/mypage/downloadReport
학생이 저장한 보고서를 다운로드 받음 
이때 res.download()라는 것을 사용하여 프론트에 넘겨줌 이것은 파일을 직접적으로 프론트에 넘겨줄수 있는 것임 실제 프론트에서 넘어온 것을 찍어보면 파일의 내용이 넘어온 것을 볼 수 있음

4. 자신의 보고서 새로 올리기 (post)
라우터 : /std/mypage/modifyReportAndReview
먼저 학생의 이름으로 report 테이블에서 저장한 이름을 찾아 fs.unlink를 통해 파일 저장되어 있던것을 삭제함. 그리고 학생이 수정한 보고서와 후기를 report 테이블과 companyReview 테이블에 새로 업데이트 시킴 이방법은 위의 등록 방법과 동일하며 넘어가는 parmas도 동일
삭제 후에 새로 저장시키는 방법이라 promise를 통해 구현 하였음
