### ISSUE TITLE
학생_기업 신청 기능 구현

### ISSUE THREAD

**Issue by chj777** [LEEHWIJIN/internsheep-front#32]

**Comment by LEEHWIJIN** [comment]
기업 신청하는 것 기능 구현
기업을 클릭하고 지원을 눌렀을때 두가지 경우로 나뉨
1. 이미 지원한 기업이 있을경우
이미 지원한 기업이 있다는 alert 창이 뜨고 아무런 요청 처리가 안됨.
2. 지원한 기업이 없을경우
지원이 완료됐다는 alert 창을 띄움
