### ISSUE TITLE
학생_기업 신청 API 구현

### ISSUE THREAD

**Issue by chj777** [LEEHWIJIN/internsheep-front#33]

**Comment by SUYEON97** [comment]
(post)
학생이 기업 신청 할 때 cName과 sName을 가지고 신청을 한다.
studentApplyCompany 테이블에 cName, sName, YN(합격여부) 가 삽입된다.
sApplyCompanyID는 자동으로 1씩 올라가며 
YN의 0으로 들어간다.(정해지지 않은 상태)

필요한 값 : cName, sName
라우터 : /std/mypage/applyCo
