### ISSUE TITLE
학생_이력서 작성하기

### ISSUE THREAD

**Issue by LEEHWIJIN** [LEEHWIJIN/internsheep-front#45]
Iter2 에서는 간단하게 이력서 데이터 주고 받는 것을 했다면 Iter3에선 완벽하게 # #

**Comment by SUYEON97** [comment]
1. 학생 이력서 작성하기 (post)
라우터 : /std/mypage/resume
params = programmingLang(json), frameworkLang(json), databaseLang(json), cloudLang(json), machineLang(json), sScore(json), sPhone, sHope(학생이 원하는 직무), sEmail, sGrade(json), sHopeTerm(학생이 원하는 직무 기간), sEnglish(json)

student 테이블에서 sID를 찾아 resume 테이블에 그 sID를 포린키로 넣고 나머지 params를 insert 한다.
이때 유저로 부터 받아오는 형식은 req.body.req.안에 값들이 적혀있다.

**mysql의 json을 적는 방식은 json의 syntex때문에 string으로 적어야한다. 그렇기 때문에 nodejs에서 mysql에 json형식으로 보내고 싶다면 `{"javascript" : 값, "html" : 값 }` 과 같은 형식으로 적어야 한다. **

2. 학생 이력서 가져오기 (get)
라우터 : /std/mypage/watchResume
student 테이블과 resume테이블을 sID로 natural join하고 sLoginID를 받아와 학생을 찾는다 그리고 resume 테이블에 있는 모든 값을 select 해온다.
만약 이력서를 작성한적이 없다면 0을 send 해주고 그렇지 않다면 값들을 json으로 보내준다.

3. 학생 이력서 수정하기 (post)
라우터 : /std/mypage/modifyResume
params = programmingLang(json), frameworkLang(json), databaseLang(json), cloudLang(json), machineLang(json), sScore(json), sPhone, sHope(학생이 원하는 직무), sEmail, sGrade(json), sHopeTerm(학생이 원하는 직무 기간), sEnglish(json)

student 테이블에서 sID를 찾아 resume 테이블에 그 sID를 찾고 params들을 update 한다.
이때 유저로 부터 받아오는 형식은 req.body.req.안에 값들이 적혀있다.
