### ISSUE TITLE
학생_찜한 기업 목록 보기 API 구현

### ISSUE THREAD

**Issue by LEEHWIJIN** [LEEHWIJIN/internsheep-front#59]

**Comment by SUYEON97** [comment]
라우터 : /std/mypage/checkPickCo -> 학생이 선택한 기업을 찜했는지 안했는지 확인함 
              /std/mypage/postStdPickCo -> 학생이 선택한 기업을 찜함
             /std/mypage/deleteStdPickCo -> 학생이 선택한 기업을 찜한 목록에서 삭제함
