### ISSUE TITLE
기업_선발학생관리 기능 구현 

### ISSUE THREAD

**Issue by LEEHWIJIN** [LEEHWIJIN/internsheep-front#67]

**Comment by hol819** [comment]
구체적인 예외사황 구현
- 아직 지원한 학생이 없을경우 '아직 지원한 학생이 없습니다.' 라고 띄워줌
- 기간이 없거나, 공고가 없거나 하는 예외처리를 진행
- 합불 여부가 모두 결정되어야 확정이 가능하게 함
